name: LiveXYZ
main: dktapps\LiveXYZ\LiveXYZ
src-namespace-prefix: dktapps\LiveXYZ
author: dktapps
description: Show real-time player coordinates
version: 1.0.1
api: [4.0.0, 5.0.0]
commands:
  xyz:
    description: Show your coordinates real-time as you move
    permission: livexyz
    usage: /xyz
permissions:
  livexyz:
    default: true
    description: "Allows use of LiveXYZ"
